os: linux

language: python

services:
    - redis-server

python:
    - 3.6
    - 3.7
#    - pypy3.6

matrix:
  include:
    - name: "Python 3.8"
      python: 3.8
      dist: disco

install:
    - pip install codecov

script:
    - coverage run setup.py test

after_success:
    - codecov
