os: linux

language: python

dist: bionic 

services:
    - redis-server

python:
    - 3.6
    - 3.7
    - 3.8
#    - pypy3.6

install:
    - pip install codecov

script:
    - coverage run setup.py test

after_success:
    - codecov
