os: linux

language: python

python:
    - 3.5
    - 3.6
    - pypy3.5

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
    - pip install codecov

script:
    - coverage run setup.py test

after_success:
    - codecov
