[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.poetry]
name = "roax"
version = "2.0b3"
description = "Lightweight framework for building resource-oriented applications."
readme = "README.md"
authors = ["Paul Bryan <pbryan@anode.ca>"]
homepage = "https://github.com/roax/roax/"
documentation = "https://github.com/roax/roax/tree/master/docs"
license = "MIT"
keywords = ["wsgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]

[tool.poetry.dependencies]
python = "^3.7"
isodate = "^0.6"
WebOb = "^1.8"
wrapt = "^1.12"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^2.3"
pytest = "^5.4"
pytest-cov = "^2.8"
