[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 96
target-version = ['py38']

[tool.poetry]
name = "fondat-core"
version = "3.0b30"
description = "A foundation for Python resource-oriented applications."
readme = "README.md"
authors = ["fondat-core authors"]
homepage = "https://github.com/fondat/fondat/"
documentation = "https://github.com/fondat/fondat/tree/main/docs"
license = "MIT"
keywords = ["asgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
packages = [
    { include = "fondat" }
]

[tool.poetry.dependencies]
python = "^3.9"
aiosqlite = "^0.16"
multidict = "^5.1"
wrapt = "^1.12"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pre-commit = "^2.10"
pytest = "^6.2"
pytest-asyncio = "^0.14"
pytest-cov = "^2.11"
