[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.poetry]
name = "fondat"
version = "3.0a1"
description = "A foundation for Python resource-oriented applications."
readme = "README.md"
authors = ["Fondat authors"]
homepage = "https://github.com/fondat/fondat/"
documentation = "https://github.com/fondat/fondat/tree/master/docs"
license = "MIT"
keywords = ["asgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.6"
aiosqlite = "^0.16"
isodate = "^0.6"
multidict = "^5.0"
wrapt = "^1.12"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pre-commit = "^2.9"
pytest = "^6.1"
pytest-asyncio = "^0.14"
pytest-cov = "^2.10"
